# This is a basic workflow to help you get started with Actions

name: getcoviddata

# Controls when the action will run. 
on:
  # schedule:
  #  - cron: '30 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Covid HK Data 2021
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: wars2021.csv
          # A URL containing data to fetch.
          http_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vT-Xw-QHYydz_kJCJLBqTKGbb2OF8_gisdUsduPbdR6Dp3tLbWxy_mkfRx2tMmGJ0q64uNsLLv3bbfb/pub?gid=0&single=true&output=csv&headers=0&range=A2:ZZ

      - name: Covid HK Data 2020
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: wars2020.csv
          # A URL containing data to fetch.
          http_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vSr2xYotDgnAq6bqm5Nkjq9voHBKzKNWH2zvTRx5LU0jnpccWykvEF8iB_0g7Tzo2pwzkTuM3ETlr_h/pub?gid=0&single=true&output=csv&headers=0&range=A2:ZZ

      - name: Quarantine HK Data
        uses: githubocto/flat@v2.0.2
        with:
          # The filename to use for writing data.
          downloaded_filename: occupancy_of_quarantine_centres_eng.csv
          # A URL containing data to fetch.
          http_url: https://www.chp.gov.hk/files/misc/occupancy_of_quarantine_centres_eng.csv
